services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0
    container_name: keycloak
    restart: always
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    command: ["start-dev"]
    depends_on:
      - keycloak-db

  keycloak-db:
    image: postgres:14
    container_name: keycloak-db
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_data:/var/lib/postgresql/data


  user-service:
    image: user-service
    container_name: user-service
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-service-db:5432/user_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: action
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://keycloak:8080/realms/eCommerce
    depends_on:
      - keycloak
      - user-service-db

    user-service-db:
      image: postgres:14
      container_name: user-service-db
      environment:
        POSTGRES_DB: user_service_db
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: action
      ports:
        - "5433:5432"

volumes:
  keycloak_data:
  user_service_data: